### ISSUE TITLE
Empty row at bottom!

### ISSUE THREAD

**Issue by harishpadmanabh-HP** [boguszpawlowski/ComposeCalendar#69] opened 2022-05-04 01:34 UTC
In some months an empty row is showing at the bottom and hence the height of the view is changing

**Comment by boguszpawlowski** [comment] 2022-05-04 11:58
Duplicate of https://github.com/boguszpawlowski/ComposeCalendar/issues/63

**Comment by boguszpawlowski** [comment] 2022-05-16 23:53
Progress on this issue can be followed in #63

**Closed by boguszpawlowski** 2022-05-16 23:53 UTC
